export type ToolCategory =
  | 'All'
  | 'Gardening & Yard'
  | 'Power Tools'
  | 'Home Improvement'
  | 'Cleaning & Steam'
  | 'Kitchen Appliances'
  | 'Automotive'
  | 'Ladders & Access'
  | 'Woodworking';

export type ToolCondition = 'Like New' | 'Good Condition' | 'Fair / Workhorse';

export type ToolStatus = 'available' | 'borrowed' | 'maintenance';

export type RequestStatus =
  | 'pending'
  | 'approved'
  | 'rejected'
  | 'active'
  | 'returned'
  | 'cancelled';

/**
 * neighborhoods table
 * CREATE TABLE neighborhoods (
 *   id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 *   name TEXT NOT NULL,
 *   city TEXT NOT NULL,
 *   postcode TEXT NOT NULL,
 *   created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
 *   updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
 * );
 */
export interface Neighborhood {
  id: number | string;
  name: string;
  city: string;
  postcode: string;
  created_at?: string;
  updated_at?: string;

  // UI presentation helpers
  activeMembers?: number;
  activeTools?: number;
  estimatedMoneySaved?: number;
}

/**
 * users table
 * CREATE TABLE users (
 *   id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 *   neighborhood_id INTEGER REFERENCES neighborhoods(id) ON DELETE SET NULL,
 *   name TEXT NOT NULL,
 *   email TEXT UNIQUE NOT NULL,
 *   password_hash TEXT NOT NULL,
 *   phone TEXT,
 *   role NUMERIC NOT NULL DEFAULT 1,
 *   created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
 *   updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
 * );
 */
export interface User {
  id: number | string;
  neighborhood_id?: number | string | null;
  name: string;
  email: string;
  password_hash?: string;
  phone?: string | null;
  role?: number;
  created_at?: string;
  updated_at?: string;

  // Joined / UI presentation helpers
  neighborhoodId?: number | string;
  neighborhoodName?: string;
  neighborhood_name?: string;
  postcode?: string;
  avatar?: string;
  trustScore?: number;
  totalBorrows?: number;
  totalLends?: number;
  onTimeReturnRate?: number;
  badges?: string[];
  joinedDate?: string;
  isVerified?: boolean;
  verificationMethod?: string;
}

/**
 * items table
 * CREATE TABLE items (
 *   id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 *   user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
 *   title TEXT NOT NULL,
 *   description TEXT,
 *   price NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
 *   deposit NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
 *   category TEXT NOT NULL,
 *   image_url TEXT,
 *   created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
 *   updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
 * );
 */
export interface Item {
  id: number | string;
  user_id?: number | string;
  title: string;
  description: string | null;
  price?: number;       // numeric(10,2) daily rate
  deposit?: number;     // numeric(10,2) security deposit
  category: string;
  image_url?: string | null;
  created_at?: string;
  updated_at?: string;

  // UI presentation aliases & helpers for legacy components
  brand?: string;
  model?: string;
  condition?: ToolCondition | string;
  maxDays?: number;
  instructions?: string;
  pickupNote?: string;
  imageUrl?: string;
  maintenanceFeePerDay?: number;
  depositAmount?: number;
  ownerId?: number | string;
  ownerName?: string;
  ownerAvatar?: string;
  ownerRating?: number;
  ownerBorrowsCount?: number;
  neighborhoodId?: number | string;
  neighborhoodName?: string;
  distanceKm?: number;
  locationSnippet?: string;
  status?: ToolStatus;
  createdAt?: string;
}

// Alias Item as ToolItem for backwards-compatibility
export type ToolItem = Item;

/**
 * bookings table (previously borrow_requests)
 * CREATE TABLE bookings (
 *   id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 *   item_id INTEGER NOT NULL REFERENCES items(id) ON DELETE CASCADE,
 *   user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
 *   start_date DATE NOT NULL,
 *   end_date DATE NOT NULL,
 *   total_price NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
 *   status TEXT NOT NULL DEFAULT 'pending',
 *   created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
 *   updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
 * );
 */
export interface Booking {
  id: number | string;
  item_id?: number | string;
  user_id?: number | string;
  start_date?: string;
  end_date?: string;
  total_price?: number;
  status: RequestStatus;
  created_at?: string;
  updated_at?: string;

  // Joined presentation helpers
  toolId?: number | string;
  toolTitle?: string;
  toolImage?: string;
  toolCategory?: string;
  ownerId?: number | string;
  ownerName?: string;
  borrowerId?: number | string;
  borrowerName?: string;
  borrowerAvatar?: string;
  borrowerTrust?: number;
  startDate?: string;
  endDate?: string;
  daysCount?: number;
  maintenanceFee?: number;
  depositFee?: number;
  totalPaid?: number;
  depositRefunded?: boolean;
  purposeNote?: string;
  createdAt?: string;
  updatedAt?: string;
}

// Alias Booking as BorrowRequest for backwards-compatibility
export type BorrowRequest = Booking;

/**
 * reviews table
 * CREATE TABLE reviews (
 *   id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 *   booking_id INTEGER NOT NULL REFERENCES bookings(id) ON DELETE CASCADE,
 *   rating NUMERIC(2, 1) NOT NULL,
 *   comment TEXT,
 *   created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
 *   updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
 * );
 */
export interface Review {
  id: number | string;
  booking_id?: number | string;
  rating: number;      // numeric(2,1)
  comment: string | null;
  created_at?: string;
  updated_at?: string;

  // Joined presentation helpers
  toolId?: number | string;
  toolTitle?: string;
  toolCategory?: string;
  toolImage?: string;
  targetUserId?: number | string;
  targetUserName?: string;
  reviewerId?: number | string;
  reviewerName?: string;
  reviewerAvatar?: string;
  date?: string;
  helpfulCount?: number;
  feedbackType?: string;
  wouldRecommend?: boolean;
  careRating?: number;
  punctualityRating?: number;
}

/**
 * chat messages (frontend helper)
 */
export interface ChatMessage {
  id: string;
  requestId?: string;
  toolId?: string | number;
  toolTitle?: string;
  senderId: string | number;
  senderName: string;
  senderAvatar: string;
  receiverId: string | number;
  receiverName: string;
  message: string;
  timestamp: string;
}
